# Site settings
title: Management made decision, just BOHICA.
description: "BOHICA means Bend Over Here It Comes Again. Every Developer knows the feeling."
baseurl: "https://spacanowski.github.io"

github_username: spacanowski
linkedin_username: pacanowskiszymon

# Build settings
markdown: kramdown
permalink: pretty

future: true

paginate: 6
paginate_path: "/blog/page:num/"
